version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root

  ApplicationStop:
    - location: scripts/stop.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user

  ValidateService:
    - location: scripts/health_check.sh
      runas: ec2-user


