version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Gradle build start"
      - chmod +x gradlew

  build:
    commands:
      - ./gradlew clean build -x test

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/libs/*.jar
